### PR TITLE
fix: ensure empty values are not synced

### PR DESCRIPTION
**Pull request by kabaros**
Fixes [TECH-1232](https://dhis2.atlassian.net/browse/TECH-1232)

sync-if-not-empty-after (1)

### CODE REVIEW

**Comment by Birkbjo** [comment]
How would we otherwise delete a value from a field if it's not synced? Or does this only prevent syncing if it was already empty?

**Comment by kabaros** [comment]
> How would we otherwise delete a value from a field if it's not synced? Or does this only prevent syncing if it was already empty?

it does allow deleting an existing value, but that's because of a JS peculiarity. Basically `Boolean('')` is `true` but `Boolean(' ')` (with an empty space)  is `false`. So that `isEmpty` is only true if it's empty spaces, but not if it's a string of length zero.

I could change the expression to `const hasEmptySpaces = value && value !== '' && value.trim() === ''` to be more explicit?

**Comment by Birkbjo** [comment]
> it does allow deleting an existing value, but that's because of a JS peculiarity. Basically `Boolean('')` is `true` but `Boolean(' ')` (with an empty space) is `false`. So that `isEmpty` is only true if it's empty spaces, but not if it's a string of length zero.

I see. But I think you mean the opposite? But yeah, the `value` would not be truthy in the case of empty string, so I understand how it works now. 

> I could change the expression to `const hasEmptySpaces = value && value !== '' && value.trim() === ''` to be more explicit?

I think the variable change could be beneficial, but I don't think the extra check for empty string is needed.

**Comment by kabaros** [comment]
> I see. But I think you mean the opposite? But yeah, the `value` would not be truthy in the case of empty string, so I understand how it works now.

yeah I did mean the opposite. Updated the variable name now.

**Review by Birkbjo — APPROVED** [review]

**Pull request merged**
